import type { NextConfig } from "next";
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin();

const securityHeaders = [
  {
    key: "X-Frame-Options",
    value: "DENY",
  },
  {
    key: "X-Content-Type-Options",
    value: "nosniff",
  },
  {
    key: "Referrer-Policy",
    value: "strict-origin-when-cross-origin",
  },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=()",
  },
];

const nextConfig: NextConfig = {
  poweredByHeader: false,
  reactStrictMode: true,
  outputFileTracingExcludes: {
    "/api/tools/letterhead": [
      "./python-api/**/*",
      "./tools/udf-converter/**/*",
      "./tools/ocr-text/**/*",
      "./tools/pdf-to-image/**/*",
      "./tools/pdf-to-word/**/*",
      "./tools/pdf-compress/**/*",
      "./tools/tiff-to-pdf/**/*",
      "./tools/requirements-legal.txt",
      "./public/uploads/**/*",
      "./prisma/dev.backup.db",
      "./dev.db",
      "./DEPLOYMENT.md",
      "./UDF-SETUP.md",
    ],
    "/api/tools/udf-convert": [
      "./python-api/**/*",
      "./tools/udf-converter/**/*",
      "./tools/ocr-text/**/*",
      "./tools/pdf-to-image/**/*",
      "./tools/pdf-to-word/**/*",
      "./tools/pdf-compress/**/*",
      "./tools/tiff-to-pdf/**/*",
      "./tools/requirements-legal.txt",
      "./public/uploads/**/*",
      "./prisma/dev.backup.db",
      "./dev.db",
      "./DEPLOYMENT.md",
      "./UDF-SETUP.md",
    ],
  },
  async redirects() {
    return [
      { source: "/abonelikler", destination: "/dijital-urunler", permanent: true },
      { source: "/en/abonelikler", destination: "/en/dijital-urunler", permanent: true },
      { source: "/en/digital-products", destination: "/en/dijital-urunler", permanent: true },
      {
        source: "/product/udf-donusturucu-toolkit-pro-omur-boyu-lisans",
        destination: "/hukuk-araclari-paketi",
        permanent: true,
      },
      {
        source: "/en/product/udf-donusturucu-toolkit-pro-omur-boyu-lisans",
        destination: "/en/legal-toolkit",
        permanent: true,
      },
      { source: "/favicon.ico", destination: "/icon.png", permanent: true },
      { source: "/favicon.png", destination: "/icon.png", permanent: true },
      { source: "/favicon-32x32.png", destination: "/icon.png", permanent: true },
      { source: "/favicon-16x16.png", destination: "/icon.png", permanent: true },
      { source: "/apple-touch-icon.png", destination: "/icon.png", permanent: true },
      { source: "/apple-touch-icon-precomposed.png", destination: "/icon.png", permanent: true },
      { source: "/site.webmanifest", destination: "/manifest.webmanifest", permanent: true },
      { source: "/portfolio", destination: "/projeler", permanent: true },
      { source: "/portfolio/:path*", destination: "/projeler/:path*", permanent: true },
      { source: "/en/portfolio", destination: "/en/projects", permanent: true },
      { source: "/en/portfolio/:path*", destination: "/en/projects/:path*", permanent: true },
      { source: "/belge-araclari", destination: "/hukuk-araclari-paketi", permanent: true },
      { source: "/dijital-urunler/hukuk-araclari-paketi", destination: "/hukuk-araclari-paketi", permanent: true },
      { source: "/panel/araclar", destination: "/hukuk-araclari-paketi", permanent: true },
      { source: "/panel/belge-merkezi", destination: "/hukuk-araclari-paketi", permanent: true },
      { source: "/panel/araclar/ek-klasoru", destination: "/ek-klasor-paketleme", permanent: true },
      { source: "/panel/ek-klasor-paketleme", destination: "/ek-klasor-paketleme", permanent: true },
      { source: "/panel/araclar/toplu-donustur", destination: "/toplu-donusturme", permanent: true },
      { source: "/panel/toplu-donusturme", destination: "/toplu-donusturme", permanent: true },
      { source: "/panel/araclar/docx-udf", destination: "/docx-udf-donusturucu", permanent: true },
      { source: "/panel/docx-udf-donusturucu", destination: "/docx-udf-donusturucu", permanent: true },
      { source: "/panel/araclar/gorsel-pdf", destination: "/gorsel-pdf-donusturucu", permanent: true },
      { source: "/panel/gorsel-pdf-donusturucu", destination: "/gorsel-pdf-donusturucu", permanent: true },
      { source: "/panel/araclar/ocr-metin", destination: "/ocr-metin-cikarma", permanent: true },
      { source: "/panel/ocr-metin-cikarma", destination: "/ocr-metin-cikarma", permanent: true },
      { source: "/panel/araclar/pdf-sikistir", destination: "/pdf-sikistirma", permanent: true },
      { source: "/panel/pdf-sikistirma", destination: "/pdf-sikistirma", permanent: true },
      { source: "/panel/araclar/pdf-birlestir", destination: "/pdf-birlestirme", permanent: true },
      { source: "/panel/pdf-birlestirme", destination: "/pdf-birlestirme", permanent: true },
      { source: "/panel/araclar/pdf-bol", destination: "/pdf-bolme", permanent: true },
      { source: "/panel/pdf-bolme", destination: "/pdf-bolme", permanent: true },
      { source: "/panel/araclar/pdf-gorsel", destination: "/pdf-gorsele-donustur", permanent: true },
      { source: "/panel/pdf-gorsele-donustur", destination: "/pdf-gorsele-donustur", permanent: true },
      { source: "/panel/araclar/pdf-word", destination: "/pdf-worde-donustur", permanent: true },
      { source: "/panel/pdf-worde-donustur", destination: "/pdf-worde-donustur", permanent: true },
      { source: "/panel/araclar/tiff-pdf", destination: "/tiff-pdf-donusturucu", permanent: true },
      { source: "/panel/tiff-pdf-donusturucu", destination: "/tiff-pdf-donusturucu", permanent: true },
      { source: "/hukuk-araclari-paketi/ek-klasor-paketleme", destination: "/ek-klasor-paketleme", permanent: true },
      { source: "/hukuk-araclari-paketi/toplu-donusturme", destination: "/toplu-donusturme", permanent: true },
      { source: "/hukuk-araclari-paketi/docx-udf-donusturucu", destination: "/docx-udf-donusturucu", permanent: true },
      { source: "/hukuk-araclari-paketi/gorsel-pdf-donusturucu", destination: "/gorsel-pdf-donusturucu", permanent: true },
      { source: "/hukuk-araclari-paketi/ocr-metin-cikarma", destination: "/ocr-metin-cikarma", permanent: true },
      { source: "/hukuk-araclari-paketi/pdf-sikistirma", destination: "/pdf-sikistirma", permanent: true },
      { source: "/hukuk-araclari-paketi/pdf-birlestirme", destination: "/pdf-birlestirme", permanent: true },
      { source: "/hukuk-araclari-paketi/pdf-bolme", destination: "/pdf-bolme", permanent: true },
      { source: "/hukuk-araclari-paketi/pdf-gorsele-donustur", destination: "/pdf-gorsele-donustur", permanent: true },
      { source: "/hukuk-araclari-paketi/pdf-worde-donustur", destination: "/pdf-worde-donustur", permanent: true },
      { source: "/hukuk-araclari-paketi/tiff-pdf-donusturucu", destination: "/tiff-pdf-donusturucu", permanent: true },
      { source: "/en/document-tools", destination: "/en/legal-toolkit", permanent: true },
      { source: "/en/dijital-urunler/hukuk-araclari-paketi", destination: "/en/legal-toolkit", permanent: true },
      { source: "/en/dashboard/tools", destination: "/en/legal-toolkit", permanent: true },
      { source: "/en/dashboard/document-tools", destination: "/en/legal-toolkit", permanent: true },
      { source: "/en/dashboard/tools/appendix-packager", destination: "/en/appendix-packager", permanent: true },
      { source: "/en/dashboard/appendix-packager", destination: "/en/appendix-packager", permanent: true },
      { source: "/en/dashboard/tools/batch-convert", destination: "/en/batch-converter", permanent: true },
      { source: "/en/dashboard/batch-converter", destination: "/en/batch-converter", permanent: true },
      { source: "/en/dashboard/tools/docx-to-udf", destination: "/en/docx-to-udf-converter", permanent: true },
      { source: "/en/dashboard/docx-to-udf-converter", destination: "/en/docx-to-udf-converter", permanent: true },
      { source: "/en/dashboard/tools/image-to-pdf", destination: "/en/image-to-pdf-converter", permanent: true },
      { source: "/en/dashboard/image-to-pdf-converter", destination: "/en/image-to-pdf-converter", permanent: true },
      { source: "/en/dashboard/tools/text-extraction", destination: "/en/ocr-text-extraction", permanent: true },
      { source: "/en/dashboard/ocr-text-extraction", destination: "/en/ocr-text-extraction", permanent: true },
      { source: "/en/dashboard/tools/compress-pdf", destination: "/en/pdf-compressor", permanent: true },
      { source: "/en/dashboard/pdf-compressor", destination: "/en/pdf-compressor", permanent: true },
      { source: "/en/dashboard/tools/merge-pdf", destination: "/en/pdf-merger", permanent: true },
      { source: "/en/dashboard/pdf-merger", destination: "/en/pdf-merger", permanent: true },
      { source: "/en/dashboard/tools/split-pdf", destination: "/en/pdf-splitter", permanent: true },
      { source: "/en/dashboard/pdf-splitter", destination: "/en/pdf-splitter", permanent: true },
      { source: "/en/dashboard/tools/pdf-to-images", destination: "/en/pdf-to-image-converter", permanent: true },
      { source: "/en/dashboard/pdf-to-image-converter", destination: "/en/pdf-to-image-converter", permanent: true },
      { source: "/en/dashboard/tools/pdf-to-word", destination: "/en/pdf-to-word-converter", permanent: true },
      { source: "/en/dashboard/pdf-to-word-converter", destination: "/en/pdf-to-word-converter", permanent: true },
      { source: "/en/dashboard/tools/tiff-to-pdf", destination: "/en/tiff-to-pdf-converter", permanent: true },
      { source: "/en/dashboard/tiff-to-pdf-converter", destination: "/en/tiff-to-pdf-converter", permanent: true },
      { source: "/en/legal-toolkit/appendix-packager", destination: "/en/appendix-packager", permanent: true },
      { source: "/en/legal-toolkit/batch-converter", destination: "/en/batch-converter", permanent: true },
      { source: "/en/legal-toolkit/docx-to-udf-converter", destination: "/en/docx-to-udf-converter", permanent: true },
      { source: "/en/legal-toolkit/image-to-pdf-converter", destination: "/en/image-to-pdf-converter", permanent: true },
      { source: "/en/legal-toolkit/ocr-text-extraction", destination: "/en/ocr-text-extraction", permanent: true },
      { source: "/en/legal-toolkit/pdf-compressor", destination: "/en/pdf-compressor", permanent: true },
      { source: "/en/legal-toolkit/pdf-merger", destination: "/en/pdf-merger", permanent: true },
      { source: "/en/legal-toolkit/pdf-splitter", destination: "/en/pdf-splitter", permanent: true },
      { source: "/en/legal-toolkit/pdf-to-image-converter", destination: "/en/pdf-to-image-converter", permanent: true },
      { source: "/en/legal-toolkit/pdf-to-word-converter", destination: "/en/pdf-to-word-converter", permanent: true },
      { source: "/en/legal-toolkit/tiff-to-pdf-converter", destination: "/en/tiff-to-pdf-converter", permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: securityHeaders,
      },
    ];
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**",
      },
    ],
  },
  experimental: {
    // Raise request cloning / proxy limits for large legal-toolkit uploads.
    proxyClientMaxBodySize: "500mb",
    serverActions: {
      bodySizeLimit: "500mb",
    },
  },
};

export default withNextIntl(nextConfig);
